{
  "locations": {
    "core_buoys": ["fedjeosen", "fauskane"],
    "external_validation_buoys": ["vestfjorden"],
    "study_areas": ["kristiansund", "stavanger", "bergen"]
  },

  "methods": [
    "linear",
    "pqm",
    "dagqm",
    "gpr",
    "xgboost",
    "transformer"
  ],

  "columns": {
    "time": "time",
    "hs_model": "hs",
    "hs_obs": "Significant_Wave_Height_Hm0",
    "per_model": "tm2",
    "per_obs": "Wave_Mean_Period_Tm02",
    "dir_model": "Pdir"
  },

  "validation": {
    "local_cv_folds": 4,
    "local_cv_min_train_samples": 100,
    "local_cv_min_test_samples": 20,
    "cv_time_group": "month"
  },

  "dagqm": {
    "n_direction_sectors": 8,
    "min_samples_per_sector": 80,
    "blend_global_weight": 0.35
  },

  "ml": {

    "default_features": [
      "hs",
      "tp",
      "tm2",
      "hs_sea",
      "hs_swell",
      "wind_speed_10m",
      "wind_speed_100m",
      "month_sin",
      "month_cos",
      "dir_sin",
      "dir_cos",
      "wind_dir_sin",
      "wind_dir_cos"
    ],

    "xgboost_fedjeosen": {
      "features": [],
      "tail_weight_q90": 3.0,
      "tail_weight_q95": 6.0,
      "tail_weight_q99": 10.0,
      "target_transform": "quantile_residual",
      "quantile_bias_mode": "additive",
      "n_estimators": 774,
      "max_depth": 4,
      "learning_rate": 0.06643379096520209,
      "subsample": 0.8606325362471129,
      "colsample_bytree": 0.9116534809046428,
      "gamma": 0.9028555192025108,
      "min_child_weight": 0.17142246538880077,
      "reg_alpha": 0.10192981012777959,
      "reg_lambda": 0.00012924370876714285,
      "target_eps": 1e-05,
      "random_state": 1
    },

    "xgboost_fauskane": {
      "features": [],
      "tail_weight_q90": 3.0,
      "tail_weight_q95": 5.0,
      "tail_weight_q99": 11.0,
      "target_transform": "quantile_residual",
      "quantile_bias_mode": "additive",
      "n_estimators": 535,
      "max_depth": 4,
      "learning_rate": 0.010763554975941236,
      "subsample": 0.876078207164875,
      "colsample_bytree": 0.8557799897917272,
      "gamma": 3.5565843833688886,
      "min_child_weight": 6.13005544110138,
      "reg_alpha": 0.006235171670732483,
      "reg_lambda": 9.034279869375382,
      "target_eps": 1e-05,
      "random_state": 1
    },

    "transformer_fedjeosen": {
      "features": [],
      "sequence_length": 16,
      "d_model": 16,
      "nhead": 2,
      "num_layers": 2,
      "dim_feedforward": 64,
      "dropout": 0.23772474999763743,
      "learning_rate": 0.0010663061065146412,
      "weight_decay": 4.8658944782380975e-06,
      "batch_size": 32,
      "target_transform": "quantile_residual",
      "quantile_bias_mode": "additive",
      "target_eps": 1e-05,
      "tail_weight_q90": 2.5,
      "tail_weight_q95": 4.5,
      "tail_weight_q99": 5.5,
      "target_space_loss_weight": 0.25,
      "physical_space_loss_weight": 1.0,
      "random_state": 1
    },

    "transformer_fauskane": {
      "features": [],
      "sequence_length": 13,
      "d_model": 16,
      "nhead": 2,
      "num_layers": 1,
      "dim_feedforward": 64,
      "dropout": 0.09358612544839771,
      "learning_rate": 0.00047260687180124554,
      "weight_decay": 6.296628103480019e-06,
      "batch_size": 32,
      "target_transform": "quantile_residual",
      "quantile_bias_mode": "additive",
      "target_eps": 1e-06,
      "tail_weight_q90": 3.0,
      "tail_weight_q95": 5.0,
      "tail_weight_q99": 11.0,
      "target_space_loss_weight": 0.25,
      "physical_space_loss_weight": 1.0,
      "random_state": 1
    },


    "ensemble_xgboost_fedjeosen": {
      "tail_weight_q90": 3.0,
      "tail_weight_q95": 6.0,
      "tail_weight_q99": 10.0,
      "n_estimators": 353,
      "max_depth": 3,
      "learning_rate": 0.08029279463995471,
      "subsample": 0.6157161186591958,
      "colsample_bytree": 0.6831921788603929,
      "gamma": 0.12820101786292928,
      "min_child_weight": 2.715788573033248,
      "reg_alpha": 0.032815853832876885,
      "reg_lambda": 1.5496241306207175,
      "tail_aware": true,
      "tail_strength_q95": 0.3446090203784341,
      "tail_strength_q99": 0.11990819475989949,
      "random_state": 1
    },

    "ensemble_xgboost_fauskane": {
      "tail_weight_q90": 1.5,
      "tail_weight_q95": 3.5,
      "tail_weight_q99": 5.5,
      "n_estimators": 475,
      "max_depth": 3,
      "learning_rate": 0.04718240800948774,
      "subsample": 0.8375142722976502,
      "colsample_bytree": 0.9599537852481393,
      "gamma": 0.02586689561648267,
      "min_child_weight": 3.264261707367586,
      "reg_alpha": 0.3288985575398967,
      "reg_lambda": 1.5135402412990284,
      "tail_aware": true,
      "tail_strength_q95": 0.37858664075670373,
      "tail_strength_q99": 0.7296327270094346,
      "random_state": 1
    },

    "ensemble_xgboost": {
      "tail_weight_q90": 3.0,
      "tail_weight_q95": 6.0,
      "tail_weight_q99": 7.0,
      "n_estimators": 549,
      "max_depth": 4,
      "learning_rate": 0.11285459494390473,
      "subsample": 0.9535499854561958,
      "colsample_bytree": 0.7573717389016158,
      "gamma": 0.06713512817967393,
      "min_child_weight": 5.790948207430555,
      "reg_alpha": 5.579883830268702,
      "reg_lambda": 1.3100074414778944,
      "tail_aware": true,
      "tail_strength_q95": 0.3324428258996939,
      "tail_strength_q99": 0.32840399274688264,
      "random_state": 1
    },

    "gpr": {
      "features": [],
      "max_train_samples": 1500,
      "random_state": 1,
      "n_restarts_optimizer": 2
    }
  },

  "thresholds": {
    "evt_threshold_quantile": 0.95,
    "decluster_hours": 48.0,
    "evt_min_events": 20,
    "evt_return_periods": [10, 20, 50],
    "evt_bootstrap_samples": 1000
  },

  "paths": {
    "pairs": "data/input/nora3_buoy_combined/NORA3_{location}_pairs.csv",
    "hindcast_raw": "data/input/nora3_locations/NORA3_wind_wave_{location}_1969_2025.csv",
    "corrected": "data/output/{location}/hindcast_corrected_{corr_method}.csv",
    "validation": "data/output/{location}/validation_{corr_method}.csv",
    "evt_results_root": "results/extreme_value_modelling"
  }
}
